"""
Interactive CLI for Web Research Agent.
Provides a beautiful terminal interface with real-time ReAct step streaming.
"""

import json
import logging
import os
import random
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from rich.console import Console
from rich.live import Live
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table
from rich.text import Text

console = Console()

# ASCII Art banner
ASCII_ART = r"""
██╗    ██╗███████╗██████╗     ██████╗ ███████╗███████╗███████╗ █████╗ ██████╗  ██████╗██╗  ██╗
██║    ██║██╔════╝██╔══██╗    ██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║  ██║
██║ █╗ ██║█████╗  ██████╔╝    ██████╔╝█████╗  ███████╗█████╗  ███████║██████╔╝██║     ███████║
██║███╗██║██╔══╝  ██╔══██╗    ██╔══██╗██╔══╝  ╚════██║██╔══╝  ██╔══██║██╔══██╗██║     ██╔══██║
╚███╔███╔╝███████╗██████╔╝    ██║  ██║███████╗███████║███████╗██║  ██║██║  ██║╚██████╗██║  ██║
 ╚══╝╚══╝ ╚══════╝╚═════╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
"""

VERSION = "1.3.0"
TAGLINE = "lock in, anon"

LOADING_MESSAGES = [
    "Summoning the AI overlords...",
    "Teaching robots to google...",
    "Consulting the digital oracle...",
    "Bribing search engines...",
    "Downloading the internet...",
    "Asking ChatGPT's cool cousin...",
    "Hacking the mainframe...",
    "Reading the Matrix...",
    "Brewing digital coffee...",
    "Waking up the neurons...",
    "Compiling knowledge...",
    "Unleashing the agents...",
    "Charging the flux capacitor...",
    "Spinning up the hamster wheel...",
    "Consulting the elders of the internet...",
]

logging.getLogger().setLevel(logging.WARNING)


# ─── Banner ──────────────────────────────────────────────────────────────────

def print_banner():
    lines = ASCII_ART.strip().split("\n")
    colors = ["bright_blue", "blue", "dodger_blue2", "deep_sky_blue1", "blue", "bright_blue"]
    console.print()
    for i, line in enumerate(lines):
        console.print(line, style=f"bold {colors[i % len(colors)]}")
    console.print(Text(f"v{VERSION}", style="bold yellow"), justify="center")
    console.print(Text(TAGLINE, style="italic cyan"), justify="center")
    console.print("═" * 100, style="bright_blue")
    console.print()


# ─── Config ──────────────────────────────────────────────────────────────────

def get_config_path() -> Path:
    config_dir = Path.home() / ".webresearch"
    config_dir.mkdir(exist_ok=True)
    return config_dir / "config.env"


def load_config() -> dict:
    config_path = get_config_path()
    config = {}
    if config_path.exists():
        with open(config_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    config[key.strip()] = value.strip()
    return config


def save_config(config: dict):
    config_path = get_config_path()
    with open(config_path, "w") as f:
        f.write("# Web Research Agent Configuration\n")
        f.write("# This file is automatically generated\n\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    console.print(f"✓ Configuration saved to {config_path}", style="bold green")


def setup_api_keys() -> dict:
    console.print(
        Panel.fit(
            "🔧 [bold cyan]First-time Setup[/bold cyan]\nLet's configure your API keys.",
            border_style="cyan",
        )
    )
    console.print()
    config = {}

    console.print("[bold yellow]1. Gemini API Key[/bold yellow]")
    console.print("   Get yours at: https://makersuite.google.com/app/apikey")
    gemini_key = Prompt.ask("   [green]Enter Gemini API key[/green]").strip()
    if not gemini_key:
        console.print("[bold red]✗ Gemini API key is required![/bold red]")
        sys.exit(1)
    config["GEMINI_API_KEY"] = gemini_key

    console.print("\n[bold yellow]2. Serper API Key[/bold yellow]")
    console.print("   Get yours at: https://serper.dev")
    console.print("   [dim](Free tier: 2,500 searches/month)[/dim]")
    serper_key = Prompt.ask("   [green]Enter Serper API key[/green]").strip()
    if not serper_key:
        console.print("[bold red]✗ Serper API key is required![/bold red]")
        sys.exit(1)
    config["SERPER_API_KEY"] = serper_key

    console.print("\n[bold yellow]3. Optional Settings[/bold yellow] [dim](press Enter for defaults)[/dim]")
    config["MAX_ITERATIONS"] = Prompt.ask("   [green]Max iterations[/green]", default="15")
    config["TEMPERATURE"] = Prompt.ask("   [green]Temperature[/green]", default="0.1")
    config["MAX_TOOL_OUTPUT_LENGTH"] = "5000"
    config["MODEL_NAME"] = "gemini-2.0-flash-exp"
    config["WEB_REQUEST_TIMEOUT"] = "30"
    config["CODE_EXECUTION_TIMEOUT"] = "60"

    console.print()
    save_config(config)
    console.print()
    return config


def check_config() -> dict:
    if os.path.exists(".env"):
        from dotenv import load_dotenv
        load_dotenv()
        config = {
            "GEMINI_API_KEY": os.getenv("GEMINI_API_KEY", ""),
            "SERPER_API_KEY": os.getenv("SERPER_API_KEY", ""),
            "MAX_ITERATIONS": os.getenv("MAX_ITERATIONS", "15"),
            "TEMPERATURE": os.getenv("TEMPERATURE", "0.1"),
            "MAX_TOOL_OUTPUT_LENGTH": os.getenv("MAX_TOOL_OUTPUT_LENGTH", "5000"),
            "MODEL_NAME": os.getenv("MODEL_NAME", "gemini-2.0-flash-exp"),
            "WEB_REQUEST_TIMEOUT": os.getenv("WEB_REQUEST_TIMEOUT", "30"),
            "CODE_EXECUTION_TIMEOUT": os.getenv("CODE_EXECUTION_TIMEOUT", "60"),
        }
        if config["GEMINI_API_KEY"] and config["SERPER_API_KEY"]:
            console.print("✓ Using configuration from .env file", style="bold green")
            return config

    config = load_config()
    if "GEMINI_API_KEY" not in config or "SERPER_API_KEY" not in config:
        console.print("⚠ Configuration not found or incomplete.\n", style="bold yellow")
        config = setup_api_keys()
    return config


def apply_config_to_env(config: dict):
    for key, value in config.items():
        os.environ[key] = value


# ─── History ─────────────────────────────────────────────────────────────────

def get_history_path() -> Path:
    history_dir = Path.home() / ".webresearch"
    history_dir.mkdir(exist_ok=True)
    return history_dir / "history.json"


def load_history() -> List[Dict]:
    path = get_history_path()
    if not path.exists():
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


def save_to_history(query: str, answer: str, steps: int, duration: float):
    history = load_history()
    history.insert(0, {
        "timestamp": datetime.now().isoformat(),
        "query": query,
        "answer_preview": answer[:200],
        "steps": steps,
        "duration": round(duration, 2),
    })
    path = get_history_path()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(history[:50], f, indent=2)


def view_history():
    history = load_history()
    if not history:
        console.print("No query history yet.", style="bold yellow")
        return

    console.print(Panel.fit("📚 [bold cyan]Query History[/bold cyan]", border_style="cyan"))
    console.print()

    table = Table(show_header=True, border_style="dim")
    table.add_column("#", style="cyan", width=4)
    table.add_column("Query", style="white", ratio=3)
    table.add_column("Steps", style="yellow", width=7, justify="right")
    table.add_column("Duration", style="dim", width=10, justify="right")
    table.add_column("Date", style="dim", width=19)

    shown = history[:10]
    for i, entry in enumerate(shown, 1):
        ts = entry.get("timestamp", "")[:16].replace("T", " ")
        q = entry["query"]
        table.add_row(
            str(i),
            q[:60] + ("…" if len(q) > 60 else ""),
            str(entry.get("steps", "?")),
            f"{entry.get('duration', 0):.1f}s",
            ts,
        )

    console.print(table)
    console.print()

    choice = Prompt.ask(
        "[green]Enter number to re-run[/green] (or press Enter to go back)", default=""
    )
    if choice.isdigit() and 1 <= int(choice) <= len(shown):
        entry = shown[int(choice) - 1]
        console.print(f"\n[cyan]Re-running:[/cyan] {entry['query']}\n")
        _run_query(entry["query"])


# ─── Agent initialization ────────────────────────────────────────────────────

def initialize_agent():
    """Initialize the ReAct agent. Imports are deferred so env vars are set first."""
    from webresearch.config import Config
    from webresearch.llm import LLMInterface
    from webresearch.tools import ToolManager, SearchTool, ScrapeTool, CodeExecutorTool, FileOpsTool
    from webresearch.agent import ReActAgent

    cfg = Config()
    cfg.validate()

    llm = LLMInterface(
        api_key=cfg.gemini_api_key,
        model_name=cfg.model_name,
        temperature=cfg.temperature,
    )

    tool_manager = ToolManager()
    tool_manager.register_tool(SearchTool(cfg.serper_api_key))
    tool_manager.register_tool(ScrapeTool())
    tool_manager.register_tool(CodeExecutorTool())
    tool_manager.register_tool(FileOpsTool())

    return ReActAgent(
        llm=llm,
        tool_manager=tool_manager,
        max_iterations=cfg.max_iterations,
    )


# ─── Core query runner ────────────────────────────────────────────────────────

def _run_query(query: str):
    """Execute a research query with live step-by-step output."""
    try:
        agent = initialize_agent()
    except Exception as e:
        console.print(f"✗ Error initializing agent: {str(e)}", style="bold red")
        console.print("Tip: Reconfigure API keys with option 5.", style="yellow")
        return

    start_time = datetime.now()
    step_rows: List[Dict] = []

    def make_step_table(rows: List[Dict], status: str = "") -> Table:
        title = "[bold cyan]ReAct Loop[/bold cyan]"
        if status:
            title += f" [dim]{status}[/dim]"
        t = Table(title=title, border_style="cyan", expand=True, show_lines=False)
        t.add_column("Step", style="cyan", width=5, justify="center")
        t.add_column("Thought", style="white", ratio=3)
        t.add_column("Action", style="yellow", width=22)
        t.add_column("Obs.", style="dim", width=10, justify="right")
        for r in rows:
            t.add_row(
                str(r["n"]),
                r["thought"],
                r["action"],
                f"{r['obs_len']} ch" if r["obs_len"] else "—",
            )
        return t

    answer: Optional[str] = None

    with Live(make_step_table([], "thinking…"), console=console, refresh_per_second=4) as live:
        def step_callback(iteration: int, step: Any):
            thought = step.thought
            if len(thought) > 90:
                thought = thought[:87] + "…"
            step_rows.append({
                "n": iteration,
                "thought": thought,
                "action": step.action or "—",
                "obs_len": len(step.observation or ""),
            })
            live.update(make_step_table(step_rows, f"step {iteration}"))

        answer = agent.run(query, step_callback=step_callback)
        live.update(make_step_table(step_rows, "complete ✓"))

    duration = (datetime.now() - start_time).total_seconds()

    console.print()
    console.rule("[bold green]RESULT[/bold green]", style="green")
    console.print()

    border = "yellow" if answer.startswith("⚠") else "green"
    console.print(Panel(answer, border_style=border, padding=(1, 2)))
    console.print()
    console.print(
        f"⏱  [yellow]{duration:.2f}s[/yellow]  [dim]│[/dim]  [cyan]{len(step_rows)} steps[/cyan]"
    )
    console.print()

    save_to_history(query, answer, len(step_rows), duration)

    if Confirm.ask("Save result to file?", default=False):
        filename = Prompt.ask("Filename", default="result.txt")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(f"Query: {query}\n{'=' * 80}\n\n{answer}\n\n")
            f.write(f"{'─' * 80}\nExecution time: {duration:.2f}s | Steps: {len(step_rows)}\n")
        console.print(f"✓ Saved to [cyan]{filename}[/cyan]", style="bold green")


# ─── Menu actions ─────────────────────────────────────────────────────────────

def show_menu():
    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="cyan bold")
    table.add_column(style="white")
    table.add_row("1.", "[green]🔍 Run a research query[/green]")
    table.add_row("2.", "[yellow]📁 Process tasks from file[/yellow]")
    table.add_row("3.", "[cyan]📚 View query history[/cyan]")
    table.add_row("4.", "[blue]📋 View recent logs[/blue]")
    table.add_row("5.", "[magenta]🔧 Reconfigure API keys[/magenta]")
    table.add_row("6.", "[red]👋 Exit[/red]")
    console.print(
        Panel(table, title="[bold cyan]What would you like to do?[/bold cyan]", border_style="cyan")
    )
    console.print()


def run_interactive_query():
    console.print(
        Panel.fit("🔍 [bold cyan]Research Query Mode[/bold cyan]", border_style="cyan")
    )
    console.print()
    query = Prompt.ask(
        "[green]❯[/green] Enter your research question (or type 'back' to return)"
    )
    if not query or query.lower() == "back":
        return
    _run_query(query)


def run_tasks_from_file():
    console.print(
        Panel.fit("📁 [bold cyan]Process Tasks from File[/bold cyan]", border_style="cyan")
    )
    console.print()

    filepath = Prompt.ask("[green]❯[/green] Path to tasks file (or 'back' to return)")
    if not filepath or filepath.lower() == "back":
        return

    if not os.path.exists(filepath):
        console.print(f"✗ File not found: {filepath}", style="bold red")
        return

    output_file = Prompt.ask("Output file", default="results.txt")

    console.print(f"\n[yellow]Processing tasks from:[/yellow] {filepath}")
    console.print(f"[yellow]Results will be saved to:[/yellow] {output_file}\n")

    def read_tasks(task_file: str) -> List[str]:
        with open(task_file, "r", encoding="utf-8") as f:
            tasks, current = [], []
            for line in f:
                line = line.rstrip()
                if not line:
                    if current:
                        tasks.append("\n".join(current))
                        current = []
                else:
                    current.append(line)
            if current:
                tasks.append("\n".join(current))
        return tasks

    try:
        tasks = read_tasks(filepath)
        agent = initialize_agent()
        results = []

        for i, task in enumerate(tasks, 1):
            console.print(f"[cyan][Task {i}/{len(tasks)}][/cyan] {task[:60]}…")
            start_time = datetime.now()
            try:
                answer = agent.run(task)
                duration = (datetime.now() - start_time).total_seconds()
                results.append({
                    "task": task,
                    "answer": answer,
                    "execution_time": round(duration, 2),
                    "num_steps": len(agent.get_execution_trace()),
                })
                console.print(f"[green]✓ Completed in {duration:.2f}s[/green]\n")
            except Exception as e:
                console.print(f"[red]✗ Error: {str(e)}[/red]\n")
                results.append({"task": task, "answer": "Error during processing", "error": str(e)})

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("=" * 100 + "\nWEB RESEARCH AGENT RESULTS\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("=" * 100 + "\n\n")
            for i, result in enumerate(results, 1):
                f.write(f"\n{'=' * 100}\nTASK {i}\n{'=' * 100}\n\n")
                f.write(f"TASK DESCRIPTION:\n{result['task']}\n\n{'-' * 100}\n\n")
                f.write(f"ANSWER:\n{result['answer']}\n\n")
                if result.get("error"):
                    f.write(f"ERROR: {result['error']}\n\n")
                f.write(f"Execution time: {result.get('execution_time', 'N/A')} seconds\n")
                f.write(f"Number of steps: {result.get('num_steps', 'N/A')}\n")

        console.print(f"[green]✓ All tasks completed! Results saved to {output_file}[/green]\n")

    except Exception as e:
        console.print(f"[red]✗ Error: {str(e)}[/red]\n")


def view_logs():
    logs_dir = Path("logs")
    if not logs_dir.exists() or not list(logs_dir.glob("*.log")):
        console.print("⚠ No log files found.", style="bold yellow")
        return

    log_files = sorted(logs_dir.glob("*.log"), key=lambda x: x.stat().st_mtime, reverse=True)

    console.print(Panel.fit("📋 [bold cyan]Recent Log Files[/bold cyan]", border_style="cyan"))
    console.print()

    table = Table(show_header=True, box=None)
    table.add_column("#", style="cyan", width=4)
    table.add_column("Filename", style="green")
    table.add_column("Size", style="yellow", justify="right")
    table.add_column("Modified", style="white")

    for i, log_file in enumerate(log_files[:5], 1):
        size = log_file.stat().st_size / 1024
        time_str = datetime.fromtimestamp(log_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S")
        table.add_row(str(i), log_file.name, f"{size:.1f} KB", time_str)

    console.print(table)
    console.print()

    choice = Prompt.ask("[green]Enter number to view[/green] (or press Enter to skip)", default="")

    if choice.isdigit() and 1 <= int(choice) <= len(log_files[:5]):
        log_file = log_files[int(choice) - 1]
        with open(log_file, "r", encoding="utf-8") as f:
            lines = f.read().split("\n")

        console.print()
        console.rule(f"[bold cyan]Log: {log_file.name}[/bold cyan]", style="cyan")
        console.print()

        if len(lines) > 100:
            console.print("[yellow][Showing last 100 lines...][/yellow]\n")
            lines = lines[-100:]

        for line in lines:
            if "ERROR" in line:
                console.print(line, style="bold red")
            elif "WARNING" in line:
                console.print(line, style="bold yellow")
            else:
                console.print(line)

        console.print()
        console.rule(style="cyan")
        console.print()


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    print_banner()

    config = check_config()
    apply_config_to_env(config)
    console.print("✓ Configuration loaded", style="bold green")
    console.print()

    while True:
        show_menu()
        choice = Prompt.ask(
            "[green]❯[/green] Choose an option", choices=["1", "2", "3", "4", "5", "6"]
        )
        console.print()

        if choice == "1":
            run_interactive_query()
        elif choice == "2":
            run_tasks_from_file()
        elif choice == "3":
            view_history()
        elif choice == "4":
            view_logs()
        elif choice == "5":
            config = setup_api_keys()
            apply_config_to_env(config)
        elif choice == "6":
            console.print(
                Panel.fit(
                    "👋 [bold cyan]Thanks for using Web Research Agent![/bold cyan]\nStay curious, anon.",
                    border_style="cyan",
                )
            )
            sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[bold cyan]Goodbye! 👋[/bold cyan]\n")
        sys.exit(0)
