api_keys:
  serper: "${SERPER_API_KEY}"
  gemini: "${GEMINI_API_KEY}"

agent:
  max_steps: 10
  timeout: 300
  memory_size: 1000

tools:
  web_search:
    rate_limit: 10
    period: 60
    max_retries: 3
    timeout: 30
  
  web_browse:
    timeout: 30
    max_size: 5242880  # 5MB
    allowed_domains: []
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  code:
    supported_languages:
      - python
      - javascript
      - typescript
      - java
    max_tokens: 2000
    temperature: 0.7

logging:
  level: "INFO"
  file: "logs/agent.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"